[build]
    publish = 'dist/'
    functions = 'functions'
    

[[redirects]]
  from = "*"
  to = "/.netlify/functions/app/"
  status = 200

[functions]
  included_files = ['functions/views/**/*.ejs']